version: '3'

services:
  turtlebot:
    container_name: humble-turtlebot
    build:
      context: .
      dockerfile: ros.Dockerfile
    restart: unless-stopped
    network_mode: host
    privileged: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0
  zenoh:
    container_name: zenoh-plugin-dds
    image: eclipse/zenoh-bridge-dds:latest
    restart: unless-stopped
    network_mode: host
    depends_on:
      - turtlebot
    command: ["-m", "peer"]
